"""
Bootstrap S&P 500 ticker → CIK mapping for SEC EDGAR ingestion.
Fetches constituent list from Wikipedia, maps to CIKs via EDGAR,
writes configs/sources/sec_sp500.yaml

Usage: python scripts/bootstrap_sp500.py [--output configs/sources/sec_sp500.yaml]
"""
import argparse
import json
import time
import requests
import pandas as pd
import yaml
from pathlib import Path
import io 

EDGAR_TICKERS_URL = "https://www.sec.gov/files/company_tickers.json"
HEADERS = {"User-Agent": "TradePlatform research@example.com"}


def fetch_sp500_tickers() -> list[str]:
    """Fetch S&P 500 constituent tickers from Wikipedia."""
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    headers = {"User-Agent": "Mozilla/5.0 (compatible; TradePlatform/1.0)"}
    resp = requests.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    tables = pd.read_html(io.StringIO(resp.text))
    df = tables[0]
    tickers = df["Symbol"].str.replace(".", "-", regex=False).tolist()
    print(f"  Found {len(tickers)} S&P 500 tickers")
    return tickers


def fetch_edgar_cik_map() -> dict[str, str]:
    """Fetch full ticker→CIK map from EDGAR. Returns {ticker: cik_padded}."""
    resp = requests.get(EDGAR_TICKERS_URL, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    data    = resp.json()
    cik_map = {}
    for entry in data.values():
        ticker = entry.get("ticker", "").upper().replace(".", "-")
        cik    = str(entry.get("cik_str", "")).zfill(10)
        if ticker and cik:
            cik_map[ticker] = cik
    print(f"  Loaded {len(cik_map)} ticker→CIK mappings from EDGAR")
    return cik_map


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="configs/sources/sec_sp500.yaml")
    args = parser.parse_args()

    print("Fetching S&P 500 constituents...")
    sp500 = fetch_sp500_tickers()

    print("Fetching EDGAR CIK map...")
    cik_map = fetch_edgar_cik_map()

    matched   = {}
    unmatched = []
    for ticker in sp500:
        cik = cik_map.get(ticker)
        if cik:
            matched[ticker] = cik
        else:
            unmatched.append(ticker)

    print(f"\nMatched:   {len(matched)}")
    print(f"Unmatched: {len(unmatched)}")
    if unmatched:
        print(f"  {unmatched}")

    output = {
        "source":      "sec",
        "description": "S&P 500 companies — auto-generated by bootstrap_sp500.py",
        "companies":   matched,
    }

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        yaml.dump(output, f, default_flow_style=False, sort_keys=True)

    print(f"\nWritten → {out_path}")


if __name__ == "__main__":
    main()
